virtual_keys = [
    {"Constant": "VK_LBUTTON", "Value": "0x01", "Description": "Left mouse button"},
    {"Constant": "VK_RBUTTON", "Value": "0x02", "Description": "Right mouse button"},
    {"Constant": "VK_MBUTTON", "Value": "0x04", "Description": "Middle mouse button"},
    {"Constant": "VK_XBUTTON1", "Value": "0x05", "Description": "X1 mouse button"},
    {"Constant": "VK_XBUTTON2", "Value": "0x06", "Description": "X2 mouse button"},
    {"Constant": "VK_CANCEL", "Value": "0x03",  "Description": "Control-break processing", },
    {"Constant": "-", "Value": "0x07", "Description": "Reserved"},
    {"Constant": "VK_BACK", "Value": "0x08", "Description": "BACKSPACE key"},
    {"Constant": "VK_TAB", "Value": "0x09", "Description": "TAB key"},
    {"Constant": "-", "Value": "0x0A-0B", "Description": "Reserved"},
    {"Constant": "VK_CLEAR", "Value": "0x0C", "Description": "CLEAR key"},
    {"Constant": "VK_RETURN", "Value": "0x0D", "Description": "ENTER key"},
    {"Constant": "-", "Value": "0x0E-0F", "Description": "Unassigned"},
    {"Constant": "VK_SHIFT", "Value": "0x10", "Description": "SHIFT key"},
    {"Constant": "VK_CONTROL", "Value": "0x11", "Description": "CTRL key"},
    {"Constant": "VK_MENU", "Value": "0x12", "Description": "ALT key"},
    {"Constant": "VK_PAUSE", "Value": "0x13", "Description": "PAUSE key"},
    {"Constant": "VK_CAPITAL", "Value": "0x14", "Description": "CAPS LOCK key"},
    {"Constant": "VK_KANA", "Value": "0x15", "Description": "IME Kana mode"},
    {"Constant": "VK_HANGUL", "Value": "0x15", "Description": "IME Hangul mode"},
    {"Constant": "VK_IME_ON", "Value": "0x16", "Description": "IME On"},
    {"Constant": "VK_JUNJA", "Value": "0x17", "Description": "IME Junja mode"},
    {"Constant": "VK_FINAL", "Value": "0x18", "Description": "IME final mode"},
    {"Constant": "VK_HANJA", "Value": "0x19", "Description": "IME Hanja mode"},
    {"Constant": "VK_KANJI", "Value": "0x19", "Description": "IME Kanji mode"},
    {"Constant": "VK_IME_OFF", "Value": "0x1A", "Description": "IME Off"},
    {"Constant": "VK_ESCAPE", "Value": "0x1B", "Description": "ESC key"},
    {"Constant": "VK_CONVERT", "Value": "0x1C", "Description": "IME convert"},
    {"Constant": "VK_NONCONVERT", "Value": "0x1D", "Description": "IME nonconvert"},
    {"Constant": "VK_ACCEPT", "Value": "0x1E", "Description": "IME accept"},
    {
        "Constant": "VK_MODECHANGE",
        "Value": "0x1F",
        "Description": "IME mode change request",
    },
    {"Constant": "VK_SPACE", "Value": "0x20", "Description": "SPACEBAR"},
    {"Constant": "VK_PRIOR", "Value": "0x21", "Description": "PAGE UP key"},
    {"Constant": "VK_NEXT", "Value": "0x22", "Description": "PAGE DOWN key"},
    {"Constant": "VK_END", "Value": "0x23", "Description": "END key"},
    {"Constant": "VK_HOME", "Value": "0x24", "Description": "HOME key"},
    {"Constant": "VK_LEFT", "Value": "0x25", "Description": "LEFT ARROW key"},
    {"Constant": "VK_UP", "Value": "0x26", "Description": "UP ARROW key"},
    {"Constant": "VK_RIGHT", "Value": "0x27", "Description": "RIGHT ARROW key"},
    {"Constant": "VK_DOWN", "Value": "0x28", "Description": "DOWN ARROW key"},
    {"Constant": "VK_SELECT", "Value": "0x29", "Description": "SELECT key"},
    {"Constant": "VK_PRINT", "Value": "0x2A", "Description": "PRINT key"},
    {"Constant": "VK_EXECUTE", "Value": "0x2B", "Description": "EXECUTE key"},
    {"Constant": "VK_SNAPSHOT", "Value": "0x2C", "Description": "PRINT SCREEN key"},
    {"Constant": "VK_INSERT", "Value": "0x2D", "Description": "INS key"},
    {"Constant": "VK_DELETE", "Value": "0x2E", "Description": "DEL key"},
    {"Constant": "VK_HELP", "Value": "0x2F", "Description": "HELP key"},
    {"Constant": "", "Value": "0x30", "Description": "0 key"},
    {"Constant": "", "Value": "0x31", "Description": "1 key"},
    {"Constant": "", "Value": "0x32", "Description": "2 key"},
    {"Constant": "", "Value": "0x33", "Description": "3 key"},
    {"Constant": "", "Value": "0x34", "Description": "4 key"},
    {"Constant": "", "Value": "0x35", "Description": "5 key"},
    {"Constant": "", "Value": "0x36", "Description": "6 key"},
    {"Constant": "", "Value": "0x37", "Description": "7 key"},
    {"Constant": "", "Value": "0x38", "Description": "8 key"},
    {"Constant": "", "Value": "0x39", "Description": "9 key"},
    {"Constant": "-", "Value": "0x3A-40", "Description": "Undefined"},
    {"Constant": "", "Value": "0x41", "Description": "A key"},
    {"Constant": "", "Value": "0x42", "Description": "B key"},
    {"Constant": "", "Value": "0x43", "Description": "C key"},
    {"Constant": "", "Value": "0x44", "Description": "D key"},
    {"Constant": "", "Value": "0x45", "Description": "E key"},
    {"Constant": "", "Value": "0x46", "Description": "F key"},
    {"Constant": "", "Value": "0x47", "Description": "G key"},
    {"Constant": "", "Value": "0x48", "Description": "H key"},
    {"Constant": "", "Value": "0x49", "Description": "I key"},
    {"Constant": "", "Value": "0x4A", "Description": "J key"},
    {"Constant": "", "Value": "0x4B", "Description": "K key"},
    {"Constant": "", "Value": "0x4C", "Description": "L key"},
    {"Constant": "", "Value": "0x4D", "Description": "M key"},
    {"Constant": "", "Value": "0x4E", "Description": "N key"},
    {"Constant": "", "Value": "0x4F", "Description": "O key"},
    {"Constant": "", "Value": "0x50", "Description": "P key"},
    {"Constant": "", "Value": "0x51", "Description": "Q key"},
    {"Constant": "", "Value": "0x52", "Description": "R key"},
    {"Constant": "", "Value": "0x53", "Description": "S key"},
    {"Constant": "", "Value": "0x54", "Description": "T key"},
    {"Constant": "", "Value": "0x55", "Description": "U key"},
    {"Constant": "", "Value": "0x56", "Description": "V key"},
    {"Constant": "", "Value": "0x57", "Description": "W key"},
    {"Constant": "", "Value": "0x58", "Description": "X key"},
    {"Constant": "", "Value": "0x59", "Description": "Y key"},
    {"Constant": "", "Value": "0x5A", "Description": "Z key"},
    {"Constant": "VK_LWIN", "Value": "0x5B", "Description": "Left Windows key"},
    {"Constant": "VK_RWIN", "Value": "0x5C", "Description": "Right Windows key"},
    {"Constant": "VK_APPS", "Value": "0x5D", "Description": "Applications key"},
    {"Constant": "-", "Value": "0x5E", "Description": "Reserved"},
    {"Constant": "VK_SLEEP", "Value": "0x5F", "Description": "Computer Sleep key"},
    {"Constant": "VK_NUMPAD0", "Value": "0x60", "Description": "Numeric keypad 0 key"},
    {"Constant": "VK_NUMPAD1", "Value": "0x61", "Description": "Numeric keypad 1 key"},
    {"Constant": "VK_NUMPAD2", "Value": "0x62", "Description": "Numeric keypad 2 key"},
    {"Constant": "VK_NUMPAD3", "Value": "0x63", "Description": "Numeric keypad 3 key"},
    {"Constant": "VK_NUMPAD4", "Value": "0x64", "Description": "Numeric keypad 4 key"},
    {"Constant": "VK_NUMPAD5", "Value": "0x65", "Description": "Numeric keypad 5 key"},
    {"Constant": "VK_NUMPAD6", "Value": "0x66", "Description": "Numeric keypad 6 key"},
    {"Constant": "VK_NUMPAD7", "Value": "0x67", "Description": "Numeric keypad 7 key"},
    {"Constant": "VK_NUMPAD8", "Value": "0x68", "Description": "Numeric keypad 8 key"},
    {"Constant": "VK_NUMPAD9", "Value": "0x69", "Description": "Numeric keypad 9 key"},
    {"Constant": "VK_MULTIPLY", "Value": "0x6A", "Description": "Multiply key"},
    {"Constant": "VK_ADD", "Value": "0x6B", "Description": "Add key"},
    {"Constant": "VK_SEPARATOR", "Value": "0x6C", "Description": "Separator key"},
    {"Constant": "VK_SUBTRACT", "Value": "0x6D", "Description": "Subtract key"},
    {"Constant": "VK_DECIMAL", "Value": "0x6E", "Description": "Decimal key"},
    {"Constant": "VK_DIVIDE", "Value": "0x6F", "Description": "Divide key"},
    {"Constant": "VK_F1", "Value": "0x70", "Description": "F1 key"},
    {"Constant": "VK_F2", "Value": "0x71", "Description": "F2 key"},
    {"Constant": "VK_F3", "Value": "0x72", "Description": "F3 key"},
    {"Constant": "VK_F4", "Value": "0x73", "Description": "F4 key"},
    {"Constant": "VK_F5", "Value": "0x74", "Description": "F5 key"},
    {"Constant": "VK_F6", "Value": "0x75", "Description": "F6 key"},
    {"Constant": "VK_F7", "Value": "0x76", "Description": "F7 key"},
    {"Constant": "VK_F8", "Value": "0x77", "Description": "F8 key"},
    {"Constant": "VK_F9", "Value": "0x78", "Description": "F9 key"},
    {"Constant": "VK_F10", "Value": "0x79", "Description": "F10 key"},
    {"Constant": "VK_F11", "Value": "0x7A", "Description": "F11 key"},
    {"Constant": "VK_F12", "Value": "0x7B", "Description": "F12 key"},
    {"Constant": "VK_F13", "Value": "0x7C", "Description": "F13 key"},
    {"Constant": "VK_F14", "Value": "0x7D", "Description": "F14 key"},
    {"Constant": "VK_F15", "Value": "0x7E", "Description": "F15 key"},
    {"Constant": "VK_F16", "Value": "0x7F", "Description": "F16 key"},
    {"Constant": "VK_F17", "Value": "0x80", "Description": "F17 key"},
    {"Constant": "VK_F18", "Value": "0x81", "Description": "F18 key"},
    {"Constant": "VK_F19", "Value": "0x82", "Description": "F19 key"},
    {"Constant": "VK_F20", "Value": "0x83", "Description": "F20 key"},
    {"Constant": "VK_F21", "Value": "0x84", "Description": "F21 key"},
    {"Constant": "VK_F22", "Value": "0x85", "Description": "F22 key"},
    {"Constant": "VK_F23", "Value": "0x86", "Description": "F23 key"},
    {"Constant": "VK_F24", "Value": "0x87", "Description": "F24 key"},
    {"Constant": "-", "Value": "0x88-8F", "Description": "Reserved"},
    {"Constant": "VK_NUMLOCK", "Value": "0x90", "Description": "NUM LOCK key"},
    {"Constant": "VK_SCROLL", "Value": "0x91", "Description": "SCROLL LOCK key"},
    {"Constant": "-", "Value": "0x92-96", "Description": "OEM specific"},
    {"Constant": "-", "Value": "0x97-9F", "Description": "Unassigned"},
    {"Constant": "VK_LSHIFT", "Value": "0xA0", "Description": "Left SHIFT key"},
    {"Constant": "VK_RSHIFT", "Value": "0xA1", "Description": "Right SHIFT key"},
    {"Constant": "VK_LCONTROL", "Value": "0xA2", "Description": "Left CONTROL key"},
    {"Constant": "VK_RCONTROL", "Value": "0xA3", "Description": "Right CONTROL key"},
    {"Constant": "VK_LMENU", "Value": "0xA4", "Description": "Left ALT key"},
    {"Constant": "VK_RMENU", "Value": "0xA5", "Description": "Right ALT key"},
    {"Constant": "VK_BROWSER_BACK", "Value": "0xA6", "Description": "Browser Back key"},
    {
        "Constant": "VK_BROWSER_FORWARD",
        "Value": "0xA7",
        "Description": "Browser Forward key",
    },
    {
        "Constant": "VK_BROWSER_REFRESH",
        "Value": "0xA8",
        "Description": "Browser Refresh key",
    },
    {"Constant": "VK_BROWSER_STOP", "Value": "0xA9", "Description": "Browser Stop key"},
    {
        "Constant": "VK_BROWSER_SEARCH",
        "Value": "0xAA",
        "Description": "Browser Search key",
    },
    {
        "Constant": "VK_BROWSER_FAVORITES",
        "Value": "0xAB",
        "Description": "Browser Favorites key",
    },
    {
        "Constant": "VK_BROWSER_HOME",
        "Value": "0xAC",
        "Description": "Browser Start and Home key",
    },
    {"Constant": "VK_VOLUME_MUTE", "Value": "0xAD", "Description": "Volume Mute key"},
    {"Constant": "VK_VOLUME_DOWN", "Value": "0xAE", "Description": "Volume Down key"},
    {"Constant": "VK_VOLUME_UP", "Value": "0xAF", "Description": "Volume Up key"},
    {
        "Constant": "VK_MEDIA_NEXT_TRACK",
        "Value": "0xB0",
        "Description": "Next Track key",
    },
    {
        "Constant": "VK_MEDIA_PREV_TRACK",
        "Value": "0xB1",
        "Description": "Previous Track key",
    },
    {"Constant": "VK_MEDIA_STOP", "Value": "0xB2", "Description": "Stop Media key"},
    {
        "Constant": "VK_MEDIA_PLAY_PAUSE",
        "Value": "0xB3",
        "Description": "Play/Pause Media key",
    },
    {"Constant": "VK_LAUNCH_MAIL", "Value": "0xB4", "Description": "Start Mail key"},
    {
        "Constant": "VK_LAUNCH_MEDIA_SELECT",
        "Value": "0xB5",
        "Description": "Select Media key",
    },
    {
        "Constant": "VK_LAUNCH_APP1",
        "Value": "0xB6",
        "Description": "Start Application 1 key",
    },
    {
        "Constant": "VK_LAUNCH_APP2",
        "Value": "0xB7",
        "Description": "Start Application 2 key",
    },
    {"Constant": "-", "Value": "0xB8-B9", "Description": "Reserved"},
    {
        "Constant": "VK_OEM_1",
        "Value": "0xBA",
        "Description": "Used for miscellaneous characters; it can vary by keyboard. For the US standard keyboard, the ;: key",
    },
    {
        "Constant": "VK_OEM_PLUS",
        "Value": "0xBB",
        "Description": "For any country/region, the + key",
    },
    {
        "Constant": "VK_OEM_COMMA",
        "Value": "0xBC",
        "Description": "For any country/region, the , key",
    },
    {
        "Constant": "VK_OEM_MINUS",
        "Value": "0xBD",
        "Description": "For any country/region, the - key",
    },
    {
        "Constant": "VK_OEM_PERIOD",
        "Value": "0xBE",
        "Description": "For any country/region, the . key",
    },
    {
        "Constant": "VK_OEM_2",
        "Value": "0xBF",
        "Description": "Used for miscellaneous characters; it can vary by keyboard. For the US standard keyboard, the /? key",
    },
    {
        "Constant": "VK_OEM_3",
        "Value": "0xC0",
        "Description": "Used for miscellaneous characters; it can vary by keyboard. For the US standard keyboard, the `~ key",
    },
    {"Constant": "-", "Value": "0xC1-DA", "Description": "Reserved"},
    {
        "Constant": "VK_OEM_4",
        "Value": "0xDB",
        "Description": "Used for miscellaneous characters; it can vary by keyboard. For the US standard keyboard, the [{ key",
    },
    {
        "Constant": "VK_OEM_5",
        "Value": "0xDC",
        "Description": "Used for miscellaneous characters; it can vary by keyboard. For the US standard keyboard, the \\\\| key",
    },
    {
        "Constant": "VK_OEM_6",
        "Value": "0xDD",
        "Description": "Used for miscellaneous characters; it can vary by keyboard. For the US standard keyboard, the ]} key",
    },
    {
        "Constant": "VK_OEM_7",
        "Value": "0xDE",
        "Description": "Used for miscellaneous characters; it can vary by keyboard. For the US standard keyboard, the '\" key",
    },
    {
        "Constant": "VK_OEM_8",
        "Value": "0xDF",
        "Description": "Used for miscellaneous characters; it can vary by keyboard.",
    },
    {"Constant": "-", "Value": "0xE0", "Description": "Reserved"},
    {"Constant": "-", "Value": "0xE1", "Description": "OEM specific"},
    {
        "Constant": "VK_OEM_102",
        "Value": "0xE2",
        "Description": "The <> keys on the US standard keyboard, or the \\\\| key on the non-US 102-key keyboard",
    },
    {"Constant": "-", "Value": "0xE3-E4", "Description": "OEM specific"},
    {"Constant": "VK_PROCESSKEY", "Value": "0xE5", "Description": "IME PROCESS key"},
    {"Constant": "-", "Value": "0xE6", "Description": "OEM specific"},
    {
        "Constant": "VK_PACKET",
        "Value": "0xE7",
        "Description": "Used to pass Unicode characters as if they were keystrokes. The VK_PACKET key is the low word of a 32-bit Virtual Key value used for non-keyboard input methods. For more information, see Remark in KEYBDINPUT, SendInput, WM_KEYDOWN, and WM_KEYUP",
    },
    {"Constant": "-", "Value": "0xE8", "Description": "Unassigned"},
    {"Constant": "-", "Value": "0xE9-F5", "Description": "OEM specific"},
    {"Constant": "VK_ATTN", "Value": "0xF6", "Description": "Attn key"},
    {"Constant": "VK_CRSEL", "Value": "0xF7", "Description": "CrSel key"},
    {"Constant": "VK_EXSEL", "Value": "0xF8", "Description": "ExSel key"},
    {"Constant": "VK_EREOF", "Value": "0xF9", "Description": "Erase EOF key"},
    {"Constant": "VK_PLAY", "Value": "0xFA", "Description": "Play key"},
    {"Constant": "VK_ZOOM", "Value": "0xFB", "Description": "Zoom key"},
    {"Constant": "VK_NONAME", "Value": "0xFC", "Description": "Reserved"},
    {"Constant": "VK_PA1", "Value": "0xFD", "Description": "PA1 key"},
    {"Constant": "VK_OEM_CLEAR", "Value": "0xFE", "Description": "Clear key"},
]
virtual_keys_data = virtual_keys 
virtualkeys = {}
for item in virtual_keys_data: 
    if item["Constant"]:
        virtualkeys[item["Constant"]] = {"Value": item["Value"], "Description": item["Description"]} 
    elif item["Description"]: 
        simplified_key = item["Description"].split()[0]
        virtualkeys[simplified_key.upper()] = {"Value": item["Value"], "Description": item["Description"]}
